### ISSUE TITLE
Fails to work after compilation

### ISSUE THREAD

**Issue by mark0978** [lorenzofox3/flexy-layout#10]
I've got a simple angular app that works with the flexylayout from the app directory, until I run grunt and try to execute it from the dist directory.  At that point, something has removed it from the list of script tags to include.

The karma tests fail saying:

```
Error: No module: flexyLayout
```

So I move it to the modules section, or the plugins section so it will be minified along with bootstrap and everything else.

The karma tests fail saying:

```
Error: No module: flexyLayout
```

If I use `grunt --force` and then try to run from the dist directory, it fails with hundreds of console errors (every update cycle maybe?)

I installed it using 

```
bower install https://github.com/lorenzofox3/flexy-layout.git
```

It is obviously setup and working before the compile/minification.  I'm just not sure why it doesn't work afterward.  Is there something special I have to do to make it work in a distributable app?

**Comment by lorenzofox3** [comment]
Hello,

I have no idea of what you are talking about.

In this repo you'll find the code for developers who want to play with the source code (in src folder) where every component of the module has its own file. 
Then there is a grunt file that will let you run two tasks : one for concatenate the different files (this will result in flexy-layout.debug.js. The other one to minify the concatanated file (flexy-layout.min.js). Both are working fine as far as I know.

If you want to use the module for your project as it is, simply take the flexy-layout.min.js (you 'll need also the css though).

then you "app directory", "distrib directory", your "compilation" have nothing to do with this module and are specific to your project. I don't even know what "compilation" mean. I guess some tasks you have defined in you gruntfile. But again these are specific to you project. 

the only thing I can tell you to help you is that 
the error you get (no module) when you run your tests is likely because your test refers to a module which asks for flexy layout as a dependency but you don't have added the file which loads flexy layout in your karma config, or in the wrong order. See the [documentation](http://karma-runner.github.io/0.10/config/configuration-file.html) for more info

Laurent
